site_name: Meteorix
nav:
  - Introduction: index.md
  - Algorithme de détection: detection.md
  - Environnement d'éxécution : env.md
  - Paramètre de compression : param.md
  - Documentation pour Flownet: docu.md
  - Inférence de Flownet: inf.md
  - Génération d'une base de données: gen.md
  - Conclusion: conclusion.md
  - Annexes: annexes.md
  - Utilisation FFMPEG : Utilisation FFMPEG.ipynb
  - Utilisation MVE : Utilisation MVE.ipynb
  - Implémentation Flownet sur em780 : implem.md
theme: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocs-jupyter
  