site_name: Meteorix
nav:
  - Introduction: index.md
  - Détection de météores: detection_meteores.md
  - Environnement d'exécution: environnement_execution.md
  - Encodage vidéo: encodage_video.md
  - FFMPEG: ffmpeg.md
  - Utilisation FFMPEG : Utilisation FFMPEG.ipynb
  - Motion Vector Extractor: motion_vector_extractor.md
  - Utilisation MVE : Utilisation MVE.ipynb
  - Flux optique: flux_optique.md
  - Définition CNN: definition_cnn.md
  - Apprentissage: apprentissage.md
  - Définition utiles: definition_utiles.md
  - Flownet: flownet.md
  - Résultats FlowNet: resultats_flownet.md
  - Conclusion: conclusion.md
  - Impacts éthiques/sociétaux: impacts_ethiques_societaux.md
  - Références: references.md
  - Annexes: annexes.md
theme: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocs-jupyter

extra_css:
  - extra.css